Upgrade makefile
Brush-Lab/OS-x86 pull request #8
Opened 2024-06-14 09:16 UTC by Indraswara

2024-06-14 09:26 UTC, Lock1 requested changes

2024-06-14 09:26 UTC, Lock1 commented on .vscode/launch.json
> +    ]
Please use LF for newline

2024-06-14 09:26 UTC, Lock1 commented on makefile
> +#OBJECTS       = src/kernel.o src/kernel-entrypoint.o src/cpu/gdt.o
Should've delete this unused code

2024-06-14 09:26 UTC, Lock1 commented on makefile
> +# SOURCE_FOLDER_KERNEL = $(SOURCE_FOLDER)/kernel
Ditto

2024-06-14 09:26 UTC, Lock1 commented on makefile
> +kernel: $(OBJECTS) #TODO: I have to update $(OBJECTS)
As `OBJECTS` already deleted, is this still needed?

2024-06-14 09:35 UTC, Lock1 commented on .vscode/launch.json
> +    ]
Also please ensure this PR only contain relevant changes

2024-06-14 09:42 UTC, Indraswara commented on makefile
> +kernel: $(OBJECTS) #TODO: I have to update $(OBJECTS)
which one? $(OBJECTS)? it still needed

![gambar](https://github.com/Brush-Lab/OS-x86/assets/69344524/659394b7-f416-4775-befa-733ca336306f)

2024-06-14 09:49 UTC, Lock1 commented on makefile
> +kernel: $(OBJECTS) #TODO: I have to update $(OBJECTS)
I see, I thought `OBJECTS` got removed completely

2024-06-16 06:26 UTC, Lock1 approved these changes

2024-06-16 06:27 UTC, merged